### ISSUE TITLE
请教预处理部分的几个问题

### ISSUE THREAD

**Issue by shuizhonghaitong** [XiaoyuanYi/WMPoetry#2]
您好，在拜读您的代码的过程中遇到了几个问题，希望可以请教一下您。
1. mulword_map，poemyun这两个dict，在yun.py中使用到了，但是它们的构建部分没有找到？
2. 得到每句的韵的规则为什么是先找two_words，然后再找three_words？
3. 您的平声字典，仄声字典是从哪里找到资源的呢？还有FunctionWords.txt fchar.txt goodwords.txt这三个都是自己总结出来的还是采用了前人发布的？
4. 关于绝句的四种句式，在GL.py中出现了很多种超出句式范围的情况为什么也能把它们划分进那四种里面？
5. tfidf或textrank是从另外一份绝句语料中训练得到的吗？还是就是corpus.txt？

**Comment by XiaoyuanYi** [comment]
您好，十分抱歉抱歉一直没注意到issue。 
1. Yun.py里韵查找需要使用一个大的语料库构建，因为我们的数据暂未开放，所以相关构建函数没有提供。yun.py已经更新，目前只保留了调用部分的代码，并且我们提供了构建好的韵数据yun.pkl。
2. 因为可能存在属于多个韵部的韵字，我们目前简单地根据统计的方式排歧，先用bi-gram，通常可能一个词来对读音(韵部排歧)，如果bi-gram无法确定，再使用三元组来排歧。
3. 平声字典和仄声字典是根据平水韵构建的，即取平水韵里所有的平声字和仄声字。FunctionWords.txt fchar.txt goodwords.txt这三个文件是我们自己整理的。
4. 我们做了简单的归纳，采用了比较常见的四种句式，对于一些可平可仄的情况可以纳入其中。少数例外情况为了简化问题就暂时没有考虑。
5. 我们论文中就是使用实验所用的语料得到的。我们目前在google drive中提供了一份处理好的版本，这是用一个较大的库处理得到的。

之前我们升级了代码的python版本和tensorflow版本，一些细节也进行了优化，如有问题欢迎提出。
