### ISSUE TITLE
关于generate_base.py的问题

### ISSUE THREAD

**Issue by shuizhonghaitong** [XiaoyuanYi/WMPoetry#3]
您好！请问generate_base.py的228行~234行用的indices是否与原先不对应，这样用indices索引出的结果是没有意义的？因为indices是新的候选序列的下标列表。

**Comment by XiaoyuanYi** [comment]
您好，十分抱歉一直没注意到issue。
因为在beam search的过程中能够，一些beam候选可能会提前生成结束(生成了句尾符</S>)，然后被移除beam，此时剩余的beam数据改变，因此对应的states， 如hidden， memory等的batch size也需要相应变化，所以重新做了索引，选取了剩余的部分。此时只需要各种状态中统一索引下标属于统一beam candidate即可。不同beam candidate之间的相互位置有变化不影响结果，因为各个beam candidate是独立的。

之前我们升级了代码的python版本和tensorflow版本，一些细节也进行了优化，如有问题欢迎提出。
