### ISSUE TITLE
aaabbbccc

### ISSUE THREAD

**Issue by chenwanyuan** [XiaoyuanYi/WMPoetry#4]

**Comment by XiaoyuanYi** [comment]
谢谢您的建议。我们readme里已经逐一写了预处理、训练、生成的步骤，提供了必要的数据，按照readme可以run起来。为了让代码结构尽可能清晰，预处理、训练、生成部分也都分别给出了，model部分的layer和主体框架graph分离开，主要graph代码部分都加了必要的注释，能和paper中的思路对应起来。如有具体的疑问，欢迎再提出，我们会尽量解答。关于开源代码整理，如果您有好的经验心得，也欢迎分享。 谢谢。
