### ISSUE TITLE
这个模型真的超级复杂代码逻辑看不懂^*_*^我都想写个pytorch版本

### ISSUE THREAD

**Issue by nlpofwhat** [XiaoyuanYi/WMPoetry#6]
这个模型真的超级复杂代码逻辑看不懂^*_*^我都想写个pytorch版本

**Comment by XiaoyuanYi** [comment]
@nlpofwhat   你好, 我们已经release了一个pytorch的版本, 在 https://github.com/THUNLP-AIPoet/WMPoetry

**Comment by nlpofwhat** [comment]
好的谢谢!------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;XiaoyuanYi&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月7日(星期一) 下午3:18
收件人:&nbsp;&quot;XiaoyuanYi/WMPoetry&quot;<WMPoetry@noreply.github.com&gt;;
抄送:&nbsp;&quot;firesoldier&quot;<952167295@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [XiaoyuanYi/WMPoetry] 这个模型真的超级复杂代码逻辑看不懂^*_*^我都想写个pytorch版本 (#6)
