### ISSUE TITLE
关于tfidf.txt

### ISSUE THREAD

**Issue by shuizhonghaitong** [XiaoyuanYi/WMPoetry#7]
您好，没太明白这个文件中每个词的tfidf是怎么来的。看tfidf的定义，不是要指定一篇文章，这篇文章中的某个词的重要度吗？但是这里的话就是一个词，一个tfidf。希望大佬能解释下，谢谢~

**Comment by XiaoyuanYi** [comment]
@shuizhonghaitong 
您好, 抱歉没能及时回复. 我们用的不是IR里面标准的TF-IDF定义. 这里我们主要是希望能够度量语料库中每个词的重要性, 然后用于后续的关键词抽取等模块.  我们把每一首诗看做一个文档,然后可以得到每个词的IDF值  log (D/(d_wi+1)), 但是我们发现仅用IDF的话, 很多低频词(经常是出现分词错误的n-gram)的IDF会很高, 所以又乘上了每个词在整个语料上的频次, f_wi, 来调和一下.  所以最终用 weight(wi) = log(f_wi+1) * log (D/(d_wi+1)) 来度量每个词的重要性.  由于形式上还是词频乘以逆文档频率的形式, 类似TF-IDF, 所以我们还是称之为TF-IDF.

现在我们所有诗歌相关的模型数据都已经转到九歌的github上维护了: https://github.com/THUNLP-AIPoet

如果您还有其他问题, 可以到上述github里面对应的repo下面开个issue, 那边我们会维护和check得频繁一些, 也能够更快回复.

**Comment by shuizhonghaitong** [comment]
非常感谢您的详细回复~跟我猜想的差不多~
